### ISSUE TITLE
crash with passive skill tree

### ISSUE THREAD

**Issue by userofbricks** [userofbricks/Expanded-Combat#43]
The following was commented on the curse forge page by [LeaMissyoy](https://legacy.curseforge.com/members/leamissyoy):

Hi, it seems to be in conflict with quiver and arrows from Passive Skill Tree, the game crash when i try to use the bow

ans load this at the beggininng of the log

[19/12/2023 00:26:54 AM] at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.handler$zzd000$expanded_combat$checkQuiver(Player.java:2249)

[19/12/2023 00:26:54 AM] at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_6298_(Player.java)

[19/12/2023 00:26:54 AM] at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BowItem.m_7203_(BowItem.java:108)

[19/12/2023 00:26:54 AM] at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:275)

**Comment by userofbricks** [comment]
at this moment my schedule is too full
