### ISSUE TITLE
When i am trying to enchant netherite battle hammer, minecraft crashes

### ISSUE THREAD

**Issue by 003hdletsee** [userofbricks/Expanded-Combat#6]
When i am trying to enchant netherite battle hammer, minecraft crashes(I used Knockback enchanted)\

Crashreport:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 25.05.21 23:13
Description: Container click

java.lang.NullPointerException: Container click
	at net.minecraft.item.TieredItem.func_82789_a(SourceFile:22) ~[?:?] {re:classloading}
	at com.userofbricks.expandedcombat.item.ECWeaponItem.func_82789_a(ECWeaponItem.java:169) ~[expanded_combat:2.1.1-1.16.5] {re:classloading}
	at net.minecraft.inventory.container.RepairContainer.func_82848_d(RepairContainer.java:106) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.inventory.container.AbstractRepairContainer.func_75130_a(SourceFile:80) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.AbstractRepairContainer$1.func_70296_d(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.inventory.Inventory.func_70299_a(SourceFile:136) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:61) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.inventory.container.Container.func_75135_a(Container.java:549) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:expanded_combat.mixins.json:ContainerAccessor,pl:mixin:A}
	at net.minecraft.inventory.container.AbstractRepairContainer.func_82846_b(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:255) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:expanded_combat.mixins.json:ContainerAccessor,pl:mixin:A}
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:expanded_combat.mixins.json:ContainerAccessor,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:379) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:539) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231044_a_(ContainerScreen.java:336) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:106) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:398) ~[?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[ForgeOptiFine%201.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.23.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.item.TieredItem.func_82789_a(SourceFile:22) ~[?:?] {re:classloading}
	at com.userofbricks.expandedcombat.item.ECWeaponItem.func_82789_a(ECWeaponItem.java:169) ~[expanded_combat:2.1.1-1.16.5] {re:classloading}
	at net.minecraft.inventory.container.RepairContainer.func_82848_d(RepairContainer.java:106) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.inventory.container.AbstractRepairContainer.func_75130_a(SourceFile:80) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.AbstractRepairContainer$1.func_70296_d(SourceFile:26) ~[?:?] {re:classloading}
	at net.minecraft.inventory.Inventory.func_70299_a(SourceFile:136) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:61) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.inventory.container.Container.func_75135_a(Container.java:549) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:expanded_combat.mixins.json:ContainerAccessor,pl:mixin:A}
	at net.minecraft.inventory.container.AbstractRepairContainer.func_82846_b(SourceFile:123) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_241440_b_(Container.java:255) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:expanded_combat.mixins.json:ContainerAccessor,pl:mixin:A}
-- Click info --
Details:
	Menu Type: minecraft:anvil
	Menu Class: net.minecraft.inventory.container.RepairContainer
	Slot Count: 39
	Slot: 31
	Button: 0
	Type: QUICK_MOVE
Stacktrace:
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:160) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:expanded_combat.mixins.json:ContainerAccessor,pl:mixin:A}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:379) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:539) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_231044_a_(ContainerScreen.java:336) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.AnvilScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:106) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:cgm.mixins.json:client.MouseHelperMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102) ~[?:?] {re:classloading}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['demidcv'/170, l='ClientLevel', x=-1506.43, y=64.00, z=327.94]]
	Chunk stats: Client Chunk Cache: 441, 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,65,-224), Chunk: (at 0,4,0 in 7,-14; contains blocks 112,0,-224 to 127,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 49265 game time, 49265 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[ForgeOptiFine%201.16.5.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.1.23.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 15772988856 bytes (15042 MB) / 17112760320 bytes (16320 MB) up to 17112760320 bytes (16320 MB)
	CPUs: 4
	JVM Flags: 10 total; -Xmn128M -Xmx16317M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.1.23.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine-OptiFine-1.16.5_HD_U_G8_pre2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.1.23.jar fml TRANSFORMATIONSERVICE 
	FML: 36.1
	Forge: net.minecraftforge:36.1.23
	FML Language Providers: 
		javafml@36.1
		minecraft@1
	Mod List: 
		forge-1.16.5-36.1.23-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		HudCompass-1.16.54-0.1.3.jar                      |HUD Compass                   |hudcompass                    |version             |DONE      |NOSIGNATURE
		Netherrocks_1.16.5_2.3.4.2.jar                    |SimpleOres:Netherrocks        |netherrocks                   |1.16.5-2.3.4.2      |DONE      |NOSIGNATURE
		cgm-1.0.1-1.16.3.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.0.1               |DONE      |NOSIGNATURE
		projectvibrantjourneys-1.16.5-3.0.3.jar           |Project: Vibrant Journeys     |projectvibrantjourneys        |1.16.5-3.0.3        |DONE      |NOSIGNATURE
		RapidLeafDecay-1.16.5-2.0.0.jar                   |Rapid Leaf Decay              |rapid_leaf_decay              |2.0.0               |DONE      |NOSIGNATURE
		SimpleCoreLib-1.16.5-2.0.5.0.jar                  |SimpleCoreLib                 |simplecorelib                 |1.16.5-2.0.5.0      |DONE      |NOSIGNATURE
		Shrines-1.16.5-1.8.1-Beta1.jar                    |Shrines                       |shrines                       |1.16.5-1.8.1-Beta1  |DONE      |NOSIGNATURE
		dungeons_plus-1.16.5-1.1.4.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.4               |DONE      |NOSIGNATURE
		locks-1.16.5-3.0.jar                              |Locks                         |locks                         |3.0                 |DONE      |NOSIGNATURE
		jei-1.16.5-7.7.0.99.jar                           |Just Enough Items             |jei                           |7.7.0.99            |DONE      |NOSIGNATURE
		prefab-1.6.5.3.jar                                |Prefab                        |prefab                        |1.6.5.3             |DONE      |NOSIGNATURE
		dungeons_mobs-1.16.5-1.0.5.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.5               |DONE      |NOSIGNATURE
		MedievalCraft-1.16.5-1.11.1.jar                   |Medieval craft                |medieval_craft                |1.10.2              |DONE      |NOSIGNATURE
		Trapcraft-1.16.53-3.3.0.jar                       |Trapcraft                     |trapcraft                     |task ':jar' property|DONE      |NOSIGNATURE
		justplayerheads_1.16.5-1.6.jar                    |Just Player Heads             |justplayerheads               |1.6                 |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.1.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.1      |DONE      |NOSIGNATURE
		Patchouli-1.16.4-51.jar                           |Patchouli                     |patchouli                     |1.16.4-51           |DONE      |NOSIGNATURE
		gravestone-1.16.5-1.0.6.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.6        |DONE      |NOSIGNATURE
		collective-1.16.5-2.26.jar                        |Collective                    |collective                    |2.26                |DONE      |NOSIGNATURE
		YungsExtras-Forge-1.16.4-1.0.jar                  |YUNG's Extras                 |yungsextras                   |Forge-1.16.4-1.0    |DONE      |NOSIGNATURE
		performant-1.16.2-5-3.56m.jar                     |Performant                    |performant                    |3.56m               |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-6.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-6      |DONE      |NOSIGNATURE
		obfuscate-0.6.0-1.16.3.jar                        |Obfuscate                     |obfuscate                     |0.6.0               |DONE      |e1:59:1a:56:ec:97:b3:d0:b3:4b:25:06:1f:83:b0:f4:fd:0c:24:e3:6d:ea:94:b1:9f:22:b0:38:13:60:88:ea
		dungeoncrawl-1_16_3-2_2_4.jar                     |Dungeon Crawl                 |dungeoncrawl                  |2.2.4               |DONE      |NOSIGNATURE
		wizardstaff-1.16.5-1.6.0.jar                      |Wizard Staff                  |wizard-staff                  |1.16.5-1.6.0        |DONE      |NOSIGNATURE
		simpleplanes-1.16.5-4.4.1.jar                     |Simple Planes                 |simpleplanes                  |1.16.5-4.4.1        |DONE      |NOSIGNATURE
		architectury-1.15.13-forge.jar                    |Architectury                  |architectury                  |1.15.13             |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |DONE      |NOSIGNATURE
		ferritecore-2.0.4-forge.jar                       |Ferrite Core                  |ferritecore                   |2.0.4               |DONE      |41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		JEITweaker-1.16.5-1.0.1.15.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.15            |DONE      |NOSIGNATURE
		JustEnoughResources-1.16.3-0.12.0.100.jar         |Just Enough Resources         |jeresources                   |0.12.0.100          |DONE      |NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.294.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.294           |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.23-universal.jar                |Forge                         |forge                         |36.1.23             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		tl_skin_cape_forge_1.16.5-1.17.jar                |TLSkinCape                    |tlskincape                    |1.17                |DONE      |19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		expanded_combat-2.1.1-1.16.5.jar                  |Expanded Combat               |expanded_combat               |2.1.1               |DONE      |NOSIGNATURE
		SimpleOres2-1.16.5-2.4.4.0.jar                    |Simple Ores                   |simpleores                    |1.16.5-2.4.4.0      |DONE      |NOSIGNATURE
		structure_gel-1.16.5-1.7.7.jar                    |Structure Gel API             |structure_gel                 |1.7.7               |DONE      |NOSIGNATURE
		ironchest_1.16.4_11.2.10.jar                      |Iron Chests                   |ironchest                     |1.16.4-11.2.10      |DONE      |NOSIGNATURE
		dungeons_gear-1.16.5-3.0.14.jar                   |Dungeons Gear                 |dungeons_gear                 |3.0.14              |DONE      |NOSIGNATURE
		antiqueatlas_1.16.54_5.4.4_forge.jar              |Antique Atlas                 |antiqueatlas                  |5.4.4-forge         |DONE      |NOSIGNATURE
		xptome-1.16.5-v2.1.2.jar                          |XP Tome                       |xpbook                        |v2.1.2              |DONE      |NOSIGNATURE
	Crash Report UUID: 64a15d2c-465a-40a0-a989-782cae126918
	Patchouli open book context: n/a
	Launched Version: ForgeOptiFine 1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.71, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: Русский (Россия)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
	OptiFine Version: OptiFine_1.16.5_HD_U_G8_pre2
	OptiFine Build: 20210305-002749
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by userofbricks** [comment]
thanks I'll see what I can do

**Comment by userofbricks** [comment]
very simple fix. I was letting the repair material method end up conpairing if null was a repair item and that causes a crash if the second item in the anvil is not the correct repair item.
